name: job execution flow

on:
  workflow_dispatch:


jobs:
  tkn:
    runs-on: ubuntu-latest
    steps:
      - name: my first
        run:  |
          mkdir output
          echo "Bagha" >> ./output/mylognew.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: all-output
          path: ./output/mylognew.txt
  second-job:
    needs: tkn
    runs-on: ubuntu-latest
    steps:
      - name: my second
        run:  |
          mkdir output
          echo "sibun" >> ./ouput/mylog.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: all-output
          path: ./output/mylog.txt
  third-job:
    needs: [tkn , second-job]
    if: ${{ failure () || cancelled () }}
    runs-on: ubuntu-latest
    steps:
      - name: my third
        run:  |
          echo "julusibun"
  
  
