name: job execution flow

on:
  workflow_dispatch:


jobs:
  tkn:
    runs-on: ubuntu-latest
    steps:
      - name: my first
        run:  |
          mkdir output
          echo "Bagha" >> ./output/mylognew.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: my-first-artifact
          path: ./output/mylognew.txt
  second-job:
    needs: tkn
    runs-on: ubuntu-latest
    steps:
      - name: my-second
        run:  |
          mkdir output
          echo "sibun" >> ./output/mylog.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: my-second-artifact
          path: ./output/mylog.txt
  third-job:
    needs: [tkn , second-job]
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:  
          name:  |
            my-first-artifact
            my-second-artifact
          path: ./output
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: all-output
          path: ./output
      - name: my third
        run:  |
          echo "julusibun"
          
  
  
